### PR TITLE
Fix inconsistent click handler args + update docs

### PR DESCRIPTION
**Pull request by timotheeg**
Fix small typo in the click handler (`notification.message` is `undefined`; should have been `notification,message`)

Also exposes the `click` handler in the readme documentation.

### CODE REVIEW

**Comment by timotheeg** [comment]
I've also added one extra commit to fix the documentation of the callbacks: `the notifications message` should be `the notification's message` 😅

**Comment by sandlerr** [comment]
nice catch @timotheeg ! Not sure on convention in this project- does the compiled file need to be updated as part of this PR?

**Comment by timotheeg** [comment]
> does the compiled file need to be updated as part of this PR?

Good question! The previous few PRs don't seem to touch the compiled files. Let me know your preference @stanlemon.

**Comment by stanlemon** [comment]
Nice catch indeed!  I can handle updating the compiled files. Thanks for your contribution @timotheeg!

**Pull request merged**
