### PR TITLE
Bower is missing the css

### PR DESCRIPTION
**Pull request by patrikx3**
I added the missing settings.

https://github.com/stanlemon/jGrowl/issues/57

### CODE REVIEW

**Comment by patrikx3** [comment]
Added simple test.

https://github.com/stanlemon/jGrowl/issues/57

**Comment by patrikx3** [comment]
Completed. Done with perfect Gruntfile.js

**Comment by stanlemon** [comment]
I'm not sure I see the value in the test on this one.  Any chance we could just do the changes to bower.json?

**Comment by patrikx3** [comment]
You can delete this because I created a new fork...

**Pull request closed without merging**
