### PR TITLE
Remove word-break

### PR DESCRIPTION
**Pull request by curtisgibby**
undo changes from #46

### CODE REVIEW

**Comment by stanlemon** [comment]
+1 thanks for your contribution!

**Comment by curtisgibby** [comment]
Any idea when this will show up in a release? I'm using CDNjs.com in my project. Do you need to bump the release number to trigger a rebuild of the CSS from the LESS?

**Comment by stanlemon** [comment]
I was traveling for work this past week and wasn't able to do this right away.  The new release has been cut, and it should be on npm.  CDNjs.com will update based upon the tag, so that should happen automatically here at some point.

**Comment by curtisgibby** [comment]
Thanks, it looks like it's propagated out to CDNjs.com now.

**Pull request merged**
