### PR TITLE
Update the closertemplate

### PR DESCRIPTION
**Pull request by DiomedesDominguez**
Were not being considered the options for the multiple notifications condition. Also, the latest version in the CDN is 1.4.6

### CODE REVIEW

**Comment by DiomedesDominguez** [comment]
In the current version, 1.4.6, it wasn't considering the following configuration for multiple notifications:
```javascript
$.jGrowl("El Captcha es obligatorio", { header: "Importante", theme: "bg-red", closerTemplate:"<div>[ cerrar todos ]</div>" });
```

jgrowl-error

This PR fix this
jgrowl-fix

**Comment by stanlemon** [comment]
@DiomedesDominguez if you are still interested in this PR can you please recreate without all of the whitespace changes?

**Comment by DiomedesDominguez** [comment]
In te current CDN version, 1.4.8, the behavior is the same, https://jsfiddle.net/jgat52v8/

**Comment by stanlemon** [comment]
This option is not intended to be set at the per notification level, but rather to be overriden for the defaults for the whole library, like in this example:
https://github.com/stanlemon/jGrowl/blob/master/examples/jgrowl.html#L82

**Pull request closed without merging**
